### PR TITLE
Fix TextField for 1.14

### PR DESCRIPTION
**Pull request by hnOsmium0001**
- Replace LWJGL Keyboard with GLFW
- Split 1.12 input logic into charTyped event
- Add moving cursor by words when pressing down the control key
    - See ctrl + arrow keys in browser

### CODE REVIEW

**Comment by McJty** [comment]
Why did you close this? I must admit I didn't notice it as first but is it no longer relevant?

**Comment by hnOsmium0001** [comment]
Since you updated `TextField.java` I just assumed all issues has been fixed (didn't bother to open it up XD). It seems like there is a few more problems: so I will reopen it
Don't have time right now but I will revisit it in a few days.

**Comment by McJty** [comment]
Ok thanks. And sorry for not looking at it earlier. I simply somehow didn't notice :-)

**Comment by hnOsmium0001** [comment]
~~I not really sure how would I test this, adding RFTools Utilities in `run/mods` will crash the game by~~
```
java.lang.NoSuchFieldError: field_176600_a
    at mcjty.rftoolsutility.setup.ClientRegistration.onModelBake(ClientRegistration.java:61)
```
~~If you can test this on your side that would be great! Note that the separate logic are working in my own mod, just not sure how would it work with this GUI system. Hopefully there won't be too much problem :)~~

Forgot forge no longer does automatic deobfuscation for mods in `.minecraft/mods`

Also #98 has been open for a long time too, you might want to check it out (it is basically the same addition as this PR but for 1.12.2)

**Comment by hnOsmium0001** [comment]
@McJty?

**Comment by McJty** [comment]
Sorry, been a bit busy. I'll check it out soon

**Comment by McJty** [comment]
I haven't forgotten this. But I first want to concentrate on fixing some of the issues in my latest batch of changes before I check this

**Pull request merged**
