### PR TITLE
Partial update to Minecraft 1.17

### PR DESCRIPTION
**Pull request by rrehbein**
- Partially updates class names and constants to their new names.
- Updates method of capability registration.

Notable remaining items:
- The removal of net.minecraftforge.common.ToolType and Block.getHarvestTool appears like it will be a structural change to resolve and will have effects with downstream modules.
- Various rendering helpers.

### CODE REVIEW

**Comment by McJty** [comment]
Hmm. Was this based on the latest 1.16 version of McJtyLib? There were massive changes that I made recently to McJtyLib 1.16. I was actually planning of throwing away the 1.17 branch because of that.

Additionally I'm not going to support 1.17. It's a dead version. I plan to move straight ahead to 1.18

**Comment by rrehbein** [comment]
Sorry, yes this was based off of the dead 1.17 branch.

**Comment by McJty** [comment]
It's it to help me with this but maybe ask first so you know my plans are. Best place for that is my discord

**Comment by rrehbein** [comment]
Yes, I was hoping to help with some of the basic remapping grunt work that the 1.18 update has.

**Comment by McJty** [comment]
I can't find you on discord. Anyway: here is my discord server: https://discord.gg/QvV9Zn8NGb

**Pull request closed without merging**
