### PR TITLE
Text field selection

### PR DESCRIPTION
**Pull request by hnOsmium0001**
Added a selection functionality to text fields (See vanilla `GuiTextField`).

### CODE REVIEW

**Comment by McJty** [comment]
That's interesting. I'll check this out later

**Comment by McJty** [comment]
So I merged this so I could test it but it is not working properly I think. First shift-arrow keys is doing nothing and if I use the arrow keys without shift I can no longer move the cursor. Can you fix this and/or explain how I'm supposed to use this?

**Comment by hnOsmium0001** [comment]
I think there is something weird with Modular Storage's text field -- it works on my end on all other machines from RFTools, except Modular Storage.
Just tested, Modular Storage's cursor doesn't move before I merged this. However, Ctrl+A and Ctrl+C/X works in it as expected.

Additionally I think you can add a remote of my fork, track the branch `TextFieldSelection` and then test it. Afterwards you can just `git branch -D TextFieldSelection` and `git remote remove WHATEVER`

**Comment by McJty** [comment]
I think I have some idea what's wrong. I'll check it out

**Comment by McJty** [comment]
Yes I fixed it. It's ok now

**Pull request merged**
