### PR TITLE
Revert "Revert "Update OC integration to the latest OC for 1.12.""

### PR DESCRIPTION
**Pull request by 12foo**
This reverts commit 452b29fb8f43344ac156af20db871d5b0cec5231.

Prerequisite for McJty/RFTools#1413.

### CODE REVIEW

**Comment by McJty** [comment]
BTW. Is this also needed on 1.10/1.11? i.e. did the api change there too or only on 1.12?

**Comment by 12foo** [comment]
This particular bit changed in 1.11 and 1.12, but not on 1.10. I made the PR against 1.12 because OC 1.7 (with the change) is the only available version there, while 1.11 has OC 1.6 and 1.7 and 1.6 doesn't have the change and could have a version issue.

**Comment by 12foo** [comment]
Hang on a second-- sorry, I read the repo wrong. OC 1.6 is not actually on MC 1.11, so it would probably be safe to make another PR against McJtyLib and RFTools for 1.11 as well. I can check that out this afternoon.

**Comment by McJty** [comment]
Is this backwards compatible? i.e. if someone updates McJtyLib with this but doesn't update RFTools? Also how does this work in relation to Open Computers? Are all my mods currently broken in combination with OC 1.7?

**Comment by 12foo** [comment]
This *should* work in a backwards-compatible way, but I'll give it a round of extra testing later now that you mention it. And they're not exactly broken, but OC support will simply not activate on OC 1.7 (so MC 1.11 and 1.12). There are no crashes, but RFTools and Deep Resonance components will not show up on the computers if you connect them.

**Comment by 12foo** [comment]
Confirming that this is backwards compatible, i.e.:

- updated McJtyLib + not updated RFTools = computers will still not recognize RFTools devices, otherwise no problems.
- updated both McJtyLib and RFTools = computers will recognize RFTools devices.

Regarding the MC 1.10 / 1.11 split, OC have changed their API exactly between Minecraft versions 1.10 and 1.11. Meaning, OC 1.7 on MC 1.10 will still work using the old API (I tested this), but OC 1.7 on 1.11 will use the new API and be backwards incompatible. So the choices for the 1.1x jar are:

- Support MC 1.11: People will be able to use OC 1.7 on MC 1.11, and no integration on 1.10.
- Support MC 1.10: People will be able to use OC 1.6 and 1.7 on MC 1.10, and no integration on 1.11.

Assuming more people play on 1.10 than on 1.11, perhaps it's better to skip the 1.11 support?

**Pull request merged**
