### PR TITLE
Fix McJtyMods/RFToolsBuilder#60

### LINKED ISSUE #60: Builder Pump Issue with replacement
RFTools builder version 3.0.17 in ATM6 1.6.14 on a server.
Forge Version is 1.16.5-36.1.32.

I have a builder with the pump card setup in the Nether. No clearing.
But the fluid blocks are not replaced with dirt.

The issue could be in McJtyLib:

https://github.com/McJtyMods/McJtyLib/blob/3e766e49f9dc22211f3df1ccdfc5ccc1de0ed8dc/src/main/java/mcjty/lib/varia/FluidTools.java#L116-L121

The lava block (`FlowingFluidBlock`) implements `IBucketPickupHander` and removes itself, but the `Runnable` for the replacement is not run in this case.

### PR DESCRIPTION
**Pull request by iTitus**
I didn't test this, but this should fix McJtyMods/RFToolsBuilder#60

### CODE REVIEW

**Comment by McJty** [comment]
I will check this later (after my holiday). Thanks

**Comment by iTitus** [comment]
Np, enjoy your holidays!

**Comment by McJty** [comment]
I'll check it out

**Comment by iTitus** [comment]
There might be an alternative way. Check if the block space is air after the fluid removal and if it is place the replacement.

**Comment by iTitus** [comment]
And there is also the `IFluidBlock` API from Forge. I don't think anyone is actually using it, but you never know...

**Comment by xchgeax** [comment]
I have also encountered this issue and after an hour of remote debugging find out that the problem is actually this lib, I have implemented almost the same solution on the latest build of the lib and the pump card works now. It has been a year already and this bug is known for at least 2 years as of now (McJtyMods/RFToolsBuilder#8). Isn't it a good idea to press a button and merge this at this point so people do not waste their time investigating why pump does not work and having fun with remote debugger instead of playing the game?

@McJty

**Comment by McJty** [comment]
Oops sorry. Indeed

**Pull request merged**
